                                                                                                                                                                                                   ?column?                                                                                                                                                                                                    
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE TABLE calls (id uuid NOT NULL, client_id uuid NOT NULL, user_id uuid NOT NULL, phone_number text NOT NULL, dial_time timestamp with time zone, duration integer(32,0), notes text, reason text, status text, created_at timestamp with time zone, updated_at timestamp with time zone);
 CREATE TABLE clients (id uuid NOT NULL, first_name text NOT NULL, last_name text NOT NULL, middle_name text, client_type text, created_at timestamp with time zone, updated_at timestamp with time zone);
 CREATE TABLE releases (id uuid NOT NULL, client_id uuid NOT NULL, user_id uuid NOT NULL, visit_id uuid NOT NULL, product_type text NOT NULL, loan_type text NOT NULL, amount numeric NOT NULL, approval_notes text, status text NOT NULL, created_at timestamp with time zone, updated_at timestamp with time zone);
 CREATE TABLE touchpoints (id uuid NOT NULL, client_id uuid NOT NULL, user_id uuid NOT NULL, visit_id uuid, call_id uuid, touchpoint_number integer(32,0) NOT NULL, type text NOT NULL, rejection_reason text, created_at timestamp with time zone, updated_at timestamp with time zone);
 CREATE TABLE users (id uuid NOT NULL, email text NOT NULL, password_hash text NOT NULL, first_name text NOT NULL, last_name text NOT NULL, middle_name text, role text, is_active boolean, created_at timestamp with time zone, updated_at timestamp with time zone);
 CREATE TABLE visits (id uuid NOT NULL, client_id uuid NOT NULL, user_id uuid NOT NULL, type text NOT NULL, time_in timestamp with time zone, time_out timestamp with time zone, odometer_arrival text, odometer_departure text, photo_url text, notes text, reason text, status text, address text, latitude real, longitude real, created_at timestamp with time zone, updated_at timestamp with time zone);
(6 rows)

