name: imu-backend
services:
  - name: web
    source_dir: /
    environment_slug: node-js
    build_command: pnpm run build
    run_command: pnpm run start
    environment_vars:
      - key: NODE_VERSION
        value: "22"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
    github:
      branch: main
      deploy_on_push: true
